// <auto-generated />
using System;
using DotNetCoreArchitecture.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetCoreArchitecture.Database.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("00000000000000_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNetCoreArchitecture.Domain.UserEntity", b =>
            {
                b.Property<long>("UserId").ValueGeneratedOnAdd().HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                b.Property<int>("Roles");
                b.Property<int>("Status");

                b.HasKey("UserId");

                b.ToTable("Users", "User");

                b.HasData(new
                {
                    UserId = 1L,
                    Roles = 3,
                    Status = 1
                });
            });

            modelBuilder.Entity("DotNetCoreArchitecture.Domain.UserLogEntity", b =>
            {
                b.Property<long>("UserLogId").ValueGeneratedOnAdd().HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                b.Property<DateTime>("DateTime");
                b.Property<int>("LogType");
                b.Property<long>("UserId");

                b.HasKey("UserLogId");

                b.HasIndex("UserId");

                b.ToTable("UsersLogs", "User");
            });

            modelBuilder.Entity("DotNetCoreArchitecture.Domain.UserEntity", b =>
            {
                b.OwnsOne("DotNetCoreArchitecture.Domain.Email", "Email", b1 =>
                {
                    b1.Property<long>("UserEntityUserId").ValueGeneratedOnAdd().HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    b1.Property<string>("Address").IsRequired().HasColumnName("Email").HasMaxLength(300);

                    b1.HasKey("UserEntityUserId");

                    b1.HasIndex("Address").IsUnique();

                    b1.ToTable("Users", "User");

                    b1.HasOne("DotNetCoreArchitecture.Domain.UserEntity")
                        .WithOne("Email")
                        .HasForeignKey("DotNetCoreArchitecture.Domain.Email", "UserEntityUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b1.HasData(new
                    {
                        UserEntityUserId = 1L,
                        Address = "administrator@administrator.com"
                    });
                });

                b.OwnsOne("DotNetCoreArchitecture.Domain.FullName", "FullName", b1 =>
                {
                    b1.Property<long>("UserEntityUserId").ValueGeneratedOnAdd().HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    b1.Property<string>("Name").IsRequired().HasColumnName("Name").HasMaxLength(100);
                    b1.Property<string>("Surname").IsRequired().HasColumnName("Surname").HasMaxLength(200);

                    b1.HasKey("UserEntityUserId");

                    b1.ToTable("Users", "User");

                    b1.HasOne("DotNetCoreArchitecture.Domain.UserEntity")
                        .WithOne("FullName")
                        .HasForeignKey("DotNetCoreArchitecture.Domain.FullName", "UserEntityUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b1.HasData(new
                    {
                        UserEntityUserId = 1L,
                        Name = "Administrator",
                        Surname = "Administrator"
                    });
                });

                b.OwnsOne("DotNetCoreArchitecture.Domain.SignIn", "SignIn", b1 =>
                {
                    b1.Property<long>("UserEntityUserId").ValueGeneratedOnAdd().HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    b1.Property<string>("Login").IsRequired().HasColumnName("Login").HasMaxLength(100);
                    b1.Property<string>("Password").IsRequired().HasColumnName("Password").HasMaxLength(500);
                    b1.Property<string>("Salt").IsRequired().HasColumnName("Salt").HasMaxLength(500);

                    b1.HasKey("UserEntityUserId");

                    b1.HasIndex("Login").IsUnique();

                    b1.ToTable("Users", "User");

                    b1.HasOne("DotNetCoreArchitecture.Domain.UserEntity")
                        .WithOne("SignIn")
                        .HasForeignKey("DotNetCoreArchitecture.Domain.SignIn", "UserEntityUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b1.HasData(new
                    {
                        UserEntityUserId = 1L,
                        Login = "admin",
                        Password = "O34uMN1Vho2IYcSM7nlXEqn57RZ8VEUsJwH++sFr0i3MSHJVx8J3PQGjhLR3s5i4l0XWUnCnymQ/EbRmzvLy8uMWREZu7vZI+BqebjAl5upYKMMQvlEcBeyLcRRTTBpYpv80m/YCZQmpig4XFVfIViLLZY/Kr5gBN5dkQf25rK8=",
                        Salt = "79005744-e69a-4b09-996b-08fe0b70cbb9"
                    });
                });
            });

            modelBuilder.Entity("DotNetCoreArchitecture.Domain.UserLogEntity", b =>
            {
                b.HasOne("DotNetCoreArchitecture.Domain.UserEntity", "User")
                    .WithMany("UsersLogs")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
        }
    }
}
